// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/amenities': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/amenities').default>>>>
    }
    '/api/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth').default>>>>
    }
    '/api/getUserListings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getUserListings').default>>>>
    }
    '/api/guestTypes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guestTypes').default>>>>
    }
    '/api/listing/:listingId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listing/[listingId].get').default>>>>
    }
    '/api/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings.post').default>>>>
    }
    '/api/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout').default>>>>
    }
    '/api/multerMiddleware': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/multerMiddleware').default>>>>
    }
    '/api/placeTypes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/placeTypes').default>>>>
    }
    '/api/user/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[userId].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.13.1_@parcel+watcher@2.4.1_@types+node@22.5.4_ioredis@5.4.1_magicast@0.3.5_rollup@4.21_mp4pnlt6mki67fidrzefbwmzhi/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}