// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/amenities': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/amenities').default>>>>
    }
    '/api/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth').default>>>>
    }
    '/api/booking': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/booking.post').default>>>>
    }
    '/api/booking/approve': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/booking/approve').default>>>>
    }
    '/api/checkFirstPayment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkFirstPayment').default>>>>
    }
    '/api/getActiveBookings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getActiveBookings').default>>>>
    }
    '/api/getHostBooking': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getHostBooking').default>>>>
    }
    '/api/getLatestPaymentDue': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getLatestPaymentDue').default>>>>
    }
    '/api/getPaymentByBookingId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getPaymentByBookingId').default>>>>
    }
    '/api/getPayments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getPayments').default>>>>
    }
    '/api/getUserBooking': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getUserBooking').default>>>>
    }
    '/api/getUserListings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getUserListings').default>>>>
    }
    '/api/guestTypes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guestTypes').default>>>>
    }
    '/api/hostlistingview/:listingId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hostlistingview/[listingId].get').default>>>>
    }
    '/api/listing/:listingId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listing/[listingId].get').default>>>>
    }
    '/api/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/listings.post').default>>>>
    }
    '/api/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout').default>>>>
    }
    '/api/multerMiddleware': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/multerMiddleware').default>>>>
    }
    '/api/notification': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notification.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications.get').default>>>>
    }
    '/api/placeTypes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/placeTypes').default>>>>
    }
    '/api/processPayment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/processPayment').default>>>>
    }
    '/api/user/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[userId].get').default>>>>
    }
    '/api/verifyEmail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verifyEmail').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._us6y7is2fwu2rszzqhbaabsbhu/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}